/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
    `java-library`
}

repositories {
    mavenLocal()
    mavenCentral()
    jcenter()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    maven {
        url = uri("https://nexus-repo.jordanosterberg.com/repository/maven-releases")
    }

    maven {
        url = uri("https://maven.pkg.github.com/OWNER/REPOSITORY")
    }

    maven {
        url = uri("https://papermc.io/repo/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.thesimplecloud.eu/artifactory/list/gradle-release-local/")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://libraries.minecraft.net/")
    }
    maven { url = uri ("https://repo.dmulloy2.net/repository/public/") }
    maven {
        url = uri ("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    }

}

dependencies {
    implementation("org.junit.jupiter:junit-jupiter-engine:5.8.2")
    implementation("org.projectlombok:lombok:1.18.22")
    annotationProcessor("org.projectlombok:lombok:1.18.22")
    implementation("com.googlecode.json-simple:json-simple:1.1.1")
    implementation("org.jetbrains:annotations:22.0.0")
    implementation("com.j256.ormlite:ormlite-core:6.1")
    implementation("com.j256.ormlite:ormlite-jdbc:6.1")
    compileOnly("io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT")
    compileOnly("com.mojang:authlib:1.5.21")
    compileOnly("eu.thesimplecloud.simplecloud:simplecloud-api:2.3.0")
    compileOnly("eu.thesimplecloud.simplecloud:simplecloud-plugin:2.3.0")
    compileOnly("dev.jcsoftware:JScoreboards:2.1.4-RELEASE")
    api(fileTree("C:/Users/caosk/Desktop/ServerAPI"))
    compileOnly("com.comphenix.protocol:ProtocolLib:4.7.0")
    compileOnly("me.clip:placeholderapi:2.11.1")

}

group = "de.chaos.mc"
version = "v1.2"
description = "LobbySystem"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}