name: LobbySystem
main: de.chaos.mc.lobbysystem.LobbySystem
author: Chaoshero5567
version: 1.2
api-version: 1.17
depend:
  - ServerAPI
commands:
  setLocation:
    usage: /setLocation [LocationName]
  test: